gem install actionmailer
gem install actionpack
gem install actionview
gem install activejob
gem install activemodel
gem install activerecord
gem install activeresource
gem install activesupport
gem install acts_as_tree
gem install addressable
gem install annotate
gem install arel
gem install ast
gem install awesome_print
gem install bcrypt
gem install bcrypt
gem install bcrypt-ruby
gem install bdoc
gem install bigdecimal
gem install bigdecimal
gem install bogus
gem install bson
gem install bson
gem install bson_ext
gem install bson_ext
gem install bubble-wrap
gem install bubble-wrap-http
gem install buftok
gem install builder
gem install bundler
gem install capybara
gem install capybara_minitest_spec
gem install carrierwave
gem install celluloid
gem install celluloid-essentials
gem install celluloid-extras
gem install celluloid-fsm
gem install celluloid-io
gem install celluloid-pool
gem install celluloid-supervision
gem install CFPropertyList
gem install childprocess
gem install claide
gem install cliver
gem install cocoapods
gem install cocoapods-core
gem install cocoapods-downloader
gem install cocoapods-plugins
gem install cocoapods-search
gem install cocoapods-stats
gem install cocoapods-trunk
gem install cocoapods-try
gem install code_analyzer
gem install coderay
gem install codesake-commons
gem install codesake-dawn
gem install coffee-rails
gem install coffee-script
gem install coffee-script-source
gem install colored
gem install concurrent-ruby
gem install coveralls
gem install css_parser
gem install cube-ruby
gem install cucumber
gem install cucumber-core
gem install curb
gem install curb
gem install cvss
gem install daemon_controller
gem install dalli
gem install database_cleaner
gem install dependor
gem install diff-lcs
gem install dnssd
gem install dnssd
gem install docile
gem install domain_name
gem install dotenv
gem install dotenv-deployment
gem install draper
gem install equalizer
gem install erubis
gem install escape
gem install execjs
gem install faraday
gem install ffi
gem install ffi
gem install forgery
gem install formatador
gem install frank-cucumber
gem install fuzzy_match
gem install gemcutter
gem install gherkin
gem install gherkin3
gem install globalid
gem install grit
gem install gruff
gem install guard
gem install guard-annotate
gem install guard-bundler
gem install guard-chef
gem install guard-coffeescript
gem install guard-compat
gem install guard-cucumber
gem install guard-haml
gem install guard-jasmine
gem install guard-jasmine-headless-webkit
gem install guard-minitest
gem install guard-rails
gem install guard-rails-assets
gem install guard-rails_best_practices
gem install guard-readme-on-github
gem install guard-sprockets
gem install guard-uglify
gem install guard-yard
gem install haml
gem install has_scope
gem install hike
gem install hitimes
gem install hitimes
gem install hpricot
gem install html2slim
gem install http
gem install http-cookie
gem install http-form_data
gem install http_parser.rb
gem install httparty
gem install i18n
gem install i18n_routing
gem install inherited_resources
gem install io-console
gem install io-console
gem install jasmine
gem install jasmine-core
gem install jasmine-headless-webkit
gem install jbuilder
gem install journey
gem install jquery-rails
gem install jquery-tmpl-rails
gem install json
gem install json
gem install json-compare
gem install json_pure
gem install justify
gem install launchy
gem install libv8
gem install libv8
gem install libxml-ruby
gem install libxml-ruby
gem install listen
gem install loofah
gem install lumberjack
gem install mail
gem install mechanize
gem install memoist
gem install memoizable
gem install metaclass
gem install method_source
gem install mime-types
gem install mime-types-data
gem install mini_magick
gem install mini_portile
gem install mini_portile2
gem install minifacture
gem install miniskirt
gem install minitest
gem install minitest-matchers
gem install minitest-spec-rails
gem install mocha
gem install molinillo
gem install mongo
gem install motion-bundler
gem install motion-cocoapods
gem install motion-frank
gem install motion-i18n
gem install motion-juxtapose
gem install motion-require
gem install motion-social
gem install motion-stump
gem install motion-support
gem install motion-testflight
gem install motion-yaml
gem install multi_json
gem install multi_test
gem install multi_xml
gem install multipart-post
gem install mysql2
gem install nap
gem install naught
gem install nenv
gem install net-http-digest_auth
gem install net-http-persistent
gem install netrc
gem install newrelic_rpm
gem install nio4r
gem install nio4r
gem install nokogiri
gem install nokogiri
gem install notiffany
gem install ntlm-http
gem install open4
gem install parser
gem install passenger
gem install passenger
gem install phantomjs
gem install plist
gem install poltergeist
gem install polyamorous
gem install polyglot
gem install posix-spawn
gem install posix-spawn
gem install power_assert
gem install pry
gem install psych
gem install psych
gem install ptools
gem install rabl
gem install rack
gem install rack-accept
gem install rack-cache
gem install rack-mount
gem install rack-openid
gem install rack-protection
gem install rack-ssl
gem install rack-test
gem install rails
gem install rails-deprecated_sanitizer
gem install rails-dom-testing
gem install rails-html-sanitizer
gem install rails-observers
gem install rails_best_practices
gem install railties
gem install rainbow
gem install rake
gem install rake-remote_task
gem install ransack
gem install rb-fsevent
gem install rb-inotify
gem install rdiscount
gem install rdiscount
gem install rdoc
gem install ref
gem install request_store
gem install require_all
gem install responders
gem install rest-client
gem install rmagick
gem install rmagick
gem install rspec
gem install rspec-core
gem install rspec-expectations
gem install rspec-mocks
gem install rspec-support
gem install ruby-openid
gem install ruby-prof
gem install ruby-prof
gem install ruby-progressbar
gem install ruby_parser
gem install rubygems-update
gem install rubyzip
gem install sass
gem install sass-rails
gem install sdoc
gem install seedbank
gem install selenium-client
gem install selenium-rc
gem install selenium-webdriver
gem install sexp_processor
gem install shellany
gem install sim_launcher
gem install simple_oauth
gem install simplecov
gem install simplecov-html
gem install sinatra
gem install sixarm_ruby_array_slice
gem install sixarm_ruby_blob
gem install sixarm_ruby_fab
gem install sixarm_ruby_hash_more
gem install sixarm_ruby_math_statistics
gem install sixarm_ruby_minitest_extensions
gem install sixarm_ruby_numeric_round
gem install sixarm_ruby_person_name
gem install sixarm_ruby_pro_logger
gem install sixarm_ruby_ramp
gem install sixarm_ruby_range_parse
gem install sixarm_ruby_rexml
gem install sixarm_ruby_time_stamp
gem install sixarm_ruby_time_terse
gem install sixarm_ruby_to_id
gem install sixarm_ruby_xml_load
gem install sixarm_ruby_xml_strip
gem install slop
gem install sprockets
gem install sprockets-rails
gem install sqlite3
gem install sqlite3
gem install ssh
gem install strong_parameters
gem install subexec
gem install sys-uname
gem install term-ansicolor
gem install terminal-table
gem install test-unit
gem install therubyracer
gem install therubyracer
gem install thor
gem install thread_safe
gem install tilt
gem install timers
gem install tins
gem install treetop
gem install turbolinks
gem install twitter
gem install tzinfo
gem install uglifier
gem install unf
gem install unf_ext
gem install unf_ext
gem install useragent
gem install valid_attribute
gem install vlad
gem install vlad-extras
gem install vlad-git
gem install webrobots
gem install websocket
gem install websocket-driver
gem install websocket-driver
gem install websocket-extensions
gem install xcodeproj
gem install xcodeproj
gem install xml-simple
gem install xpath
gem install yard
